# parameters for distributed_tf_node
min_distance_odom: 0.05
max_time_between_poses: 99999

transforms:
  - origin: "{veh}/footprint"
    target: "tag/{tag_id}"
    translation: [0.008, 0, 0.13]
    rotation: [3.14, 0, -1.5708]
