# parameters for distributed_tf_node
min_distance_odom: 0.05
max_time_between_poses: 99999

transforms:
  - origin: "{veh}/tag_mount"
    target: "tag/{tag_id}"
    translation: [0, 0, 0]
    rotation: [0, 0, 0]
